"""initial_schema

Revision ID: ea1677d7bf47
Revises:
Create Date: 2026-07-16 16:02:02.154281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1677d7bf47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='환자 성명'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='환자 나이'),
    sa.Column('gender', sa.Enum('M', 'F', name='genderenum', native_enum=False), nullable=True, comment='환자 성별'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='환자 연락처, 국내 전화번호로 한정'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='환자 정보 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='환자 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender'), nullable=False),
    sa.Column('department', sa.Enum('MEDICAL', 'DEV', 'RESEARCH', name='department'), nullable=False),
    sa.Column('role', sa.Enum('PENDING', 'STAFF', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False, comment='환자 정보 테이블 FK'),
    sa.Column('chart_number', sa.String(length=50), nullable=False, comment='환자 진료 차트 번호'),
    sa.Column('symptoms', sa.Text(), nullable=False, comment='환자 증상 기록'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='진료 정보 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='진료 정보 수정 일시'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_number')
    )
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pneumonia', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('heatmap_url', sa.String(length=255), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_results_record_id'), 'ai_analysis_results', ['record_id'], unique=False)
    op.create_table('xray_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('shooting_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xray_images')
    op.drop_index(op.f('ix_ai_analysis_results_record_id'), table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    op.drop_table('medical_records')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
